name: bullet_journal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  google_fonts: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_slidable: ^0.6.0
  flutter_local_notifications: ^6.0.0
  # image picker
  image_picker: ^0.8.2
  multi_image_picker: ^4.8.1
  get: ^4.1.4
  numberpicker: ^2.0.1
  image_cropper: ^1.4.0
  flutter_svg: ^0.22.0
  image_size_getter: ^1.0.0
  photo_view: ^0.11.1
  # color
  flex_color_picker: ^2.1.2
  # sound
  flutter_sound: ^8.1.4
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  # datetime
  intl: ^0.17.0
  date_util: ^0.1.4
  focused_menu: ^1.0.5
  table_calendar: ^3.0.0
  percent_indicator: ^3.0.1
  #location
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  popup_menu: ^1.0.5
  #csdl
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  #hive generator
  build_runner: ^2.0.3
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    
    - assets/icons/
    - assets/icons/edit/
    - assets/icons/emotion/
    - assets/icons/menu/
    - assets/fonts/google_fonts/
    - assets/gifs/
    - assets/icons/menu/
    - assets/icons/note_edit/
    - assets/images/frame/circle/
    - assets/images/frame/rectangle/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  VisibilityIcon
      fonts:
       - asset: assets/icons/my_icon/VisibilityIcon.ttf
    - family:  LoginViewIcon
      fonts:
        - asset: assets/icons/my_icon/LoginViewIcon.ttf

    - family: Anton
      fonts:
      - asset: assets/fonts/google_fonts/Anton/Anton-Regular.ttf
    - family: Caveat
      fonts:
      - asset: assets/fonts/google_fonts/Caveat/Caveat-VariableFont_wght.ttf
    - family: Courgette
      fonts:
      - asset: assets/fonts/google_fonts/Courgette/Courgette-Regular.ttf
    - family: DancingScript
      fonts:
      - asset: assets/fonts/google_fonts/DacingScript/DancingScript-Bold.ttf
      - asset: assets/fonts/google_fonts/DacingScript/DancingScript-Medium.ttf
      - asset: assets/fonts/google_fonts/DacingScript/DancingScript-Regular.ttf
      - asset: assets/fonts/google_fonts/DacingScript/DancingScript-Regular.ttf
    - family: Great_Vibes
      fonts:
      - asset: assets/fonts/google_fonts/Great_Vibes/GreatVibes-Regular.ttf
    - family: Indie_Flower
      fonts:
      - asset: assets/fonts/google_fonts/Indie_Flower/IndieFlower-Regular.ttf
    - family: Lobster
      fonts:
      - asset: assets/fonts/google_fonts/Lobster/Lobster-Regular.ttf
    - family: MonteCarlo
      fonts:
      - asset: assets/fonts/google_fonts/MonteCarlo/MonteCarlo-Regular.ttf
    - family: Pacifico
      fonts:
      - asset: assets/fonts/google_fonts/Pacifico/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Black.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-BlackItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Bold.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-BoldItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Italic.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Light.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-LightItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Medium.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-MediumItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Regular.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-Thin.ttf
      - asset: assets/fonts/google_fonts/Roboto/Roboto-ThinItalic.ttf
    - family: Roboto_Condensed
      fonts:
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-Italic.ttf
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-LightItalic.ttf
      - asset: assets/fonts/google_fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
    - family: Satisfy
      fonts: 
      - asset: assets/fonts/google_fonts/Satisfy/Satisfy-Regular.ttf
    - family: Shadows_Into_Light
      fonts:
      - asset: assets/fonts/google_fonts/Shadows_Into_Light/ShadowsIntoLight-Regular.ttf
    - family: STIXTwoText
      fonts:
      - asset: assets/fonts/google_fonts/STIXTwoText/STIXTwoText-Italic-VariableFont_wght.ttf
      - asset: assets/fonts/google_fonts/STIXTwoText/STIXTwoText-VariableFont_wght.ttf
    - family: Style_Script
      fonts:
      - asset: assets/fonts/google_fonts/Style_Script/StyleScript-Regular.ttf
    - family: WindSong
      fonts:
      - asset: assets/fonts/google_fonts/WindSong/WindSong-Medium.ttf
      - asset: assets/fonts/google_fonts/WindSong/WindSong-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
